name: testdos-github-actions
run-name:  is learning GitHub ActionsDOS
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1, actions/upload-artifact@v3
        with:
          java-version: 11.0.14
          name: linux-reports-2
          path: /target/site/serenity/
      - run:  |
          echo "MMMMMMM____----ddddd----------------------->"
          mvn verify -f pom.xml
          echo "MMMMMMM____--------------------------->"
          echo "MMMMMMM____--------------------------->"
      #- name: Store reports2
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: linux-reports-2
      #    path: /target/site/serenity/

